### ISSUE TITLE
ffmpeg.error

### ISSUE THREAD

**Issue by x-ray990011** [z-x-yang/Segment-and-Track-Anything#12]
![image](https://user-images.githubusercontent.com/127190335/233676618-f0a74b75-21fc-4b6e-8f5f-e0541ebea4f2.png)

**Comment by x-ray990011** [comment]
How can I solve the problem of not being able to save the corresponding MP4?

**Comment by x-ray990011** [comment]
Thank you for your reply. There may be a problem with my screenshot. At that time, I tried MP4 output and reported that error. I tried a new demo. pynb. Thank you again for your reply

**Comment by x-ray990011** [comment]
> Hi, in the demo.ipynb, by default the output_video has the same format as the input video, i.e. 'output_video': './assets/pl_seg.mp4', since the default fourcc is obtained from the source video. If you want a pl_seg.avi format output, i.e. 'output_video': './assets/pl_seg.avi', please go to "Save results for visualization" part, and change the line "fourcc = int(cap.get(cv2.CAP_PROP_FOURCC))" to: "fourcc = cv2.VideoWriter_fourcc(*"XVID")" or "fourcc = cv2.VideoWriter_fourcc(*"MJPG")"
> 
> Besides, we have updated the demo.ipynb, please try the new version to save the video. It supports different formats between input and output, e.g. mp4 input and avi output.

Thank you for your reply. There may be a problem with my screenshot. At that time, I tried MP4 output and reported that error. I tried a new demo. pynb. Thank you again for your reply

**Comment by x-ray990011** [comment]
> Hi, in the demo.ipynb, by default the output_video has the same format as the input video, i.e. 'output_video': './assets/pl_seg.mp4', since the default fourcc is obtained from the source video. If you want a pl_seg.avi format output, i.e. 'output_video': './assets/pl_seg.avi', please go to "Save results for visualization" part, and change the line "fourcc = int(cap.get(cv2.CAP_PROP_FOURCC))" to: "fourcc = cv2.VideoWriter_fourcc(*"XVID")" or "fourcc = cv2.VideoWriter_fourcc(*"MJPG")"
> 
> Besides, we have updated the demo.ipynb, please try the new version to save the video. It supports different formats between input and output, e.g. mp4 input and avi output.

How can I extract one specific people from the video

**Comment by x-ray990011** [comment]
> Thank you for your hard work, but the issue with saving MP4 that was previously fixed in demo.ipynb has reappeared in APP.PY. You can take a look.

![1](https://user-images.githubusercontent.com/127190335/233841146-d679d416-abc8-4c1a-b9b0-112b9516deef.JPG)

**Comment by bhack** [comment]
This cause https://github.com/opencv/opencv-python/issues/100#issuecomment-394159998

Check:
https://pypi.org/project/ffmpegcv/

**Comment by x-ray990011** [comment]
> This cause [opencv/opencv-python#100 (comment)](https://github.com/opencv/opencv-python/issues/100#issuecomment-394159998)
> 
> Check: https://pypi.org/project/ffmpegcv/



> This cause [opencv/opencv-python#100 (comment)](https://github.com/opencv/opencv-python/issues/100#issuecomment-394159998)
> 
> Check: https://pypi.org/project/ffmpegcv/

I use the same virtual environment and can generate corresponding MP4 files using demo.ipynb, but cannot generate corresponding MP4 files using app.py. I am not sure if it is a problem with my own environment or something. Could you please confirm again? Thank you for your hard work.

**Comment by x-ray990011** [comment]
> I use the same virtual environment and can generate corresponding MP4 files using demo.ipynb, but cannot generate corresponding MP4 files using app.py. I am not sure if it is a problem with my own environment or something. Could you please confirm again? Thank you for your hard work.

I use the same virtual environment and can generate corresponding MP4 files using demo.ipynb, but cannot generate corresponding MP4 files using app.py. I am not sure if it is a problem with my own environment or something. Could you please confirm again? Thank you for your hard work.

**Comment by x-ray990011** [comment]
> > > Hi, in the demo.ipynb, by default the output_video has the same format as the input video, i.e. 'output_video': './assets/pl_seg.mp4', since the default fourcc is obtained from the source video. If you want a pl_seg.avi format output, i.e. 'output_video': './assets/pl_seg.avi', please go to "Save results for visualization" part, and change the line "fourcc = int(cap.get(cv2.CAP_PROP_FOURCC))" to: "fourcc = cv2.VideoWriter_fourcc(_"XVID")" or "fourcc = cv2.VideoWriter_fourcc(_"MJPG")"
> > > Besides, we have updated the demo.ipynb, please try the new version to save the video. It supports different formats between input and output, e.g. mp4 input and avi output.
> > 
> > 
> > How can I extract one specific people from the video
> 
> The 1.0 version has been released, which supports interactive segmentation via WebUI, please have a check.

I use the same virtual environment and can generate corresponding MP4 files using demo.ipynb, but cannot generate corresponding MP4 files using app.py. I am not sure if it is a problem with my own environment or something. Could you please confirm again? Thank you for your hard work.

**Comment by x-ray990011** [comment]
> app.py 的代码部分依赖于demo.ipynb，所以问题可能与旧的demo.ipynb相同。我们正在修复它，更新版本将很快发布。



> app.py 的代码部分依赖于demo.ipynb，所以问题可能与旧的demo.ipynb相同。我们正在修复它，更新版本将很快发布。

Thank you for your reply. Your work has brought us a very good experience. Thank you very much

**Comment by bhack** [comment]
@yoxu515 Are you sure that it is going to work with this codec? Also using your default Swan example I see a warning on gradio related to the browser supported codec:
`components.py:2203: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4` 

Then the zip is visible in the UX but not the output video.

**Comment by yamy-cheng** [comment]
> @yoxu515 Are you sure that it is going to work with this codec? Also using your default Swan example I see a warning on gradio related to the browser supported codec: `components.py:2203: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4`
> 
> Then the zip is visible in the UX but not the output video.

Thank you for your reminder that there may be some incompatibilities, and we will follow up with improvements. In the current version, you can refresh by clicking the 'output-video' component, and the display will be updated.

**Comment by bhack** [comment]
>  In the current version, you can refresh by clicking the 'output-video' component, and the display will be updated.

Really? I don't see any effect.

**Comment by yamy-cheng** [comment]
> > In the current version, you can refresh by clicking the 'output-video' component, and the display will be updated.
> 
> Really? I don't see any effect.

Maybe you need to click on the bottom left corner of the 'output-video' component, which is the play button.

**Comment by yamy-cheng** [comment]
> There is any interactive area when done
> 
> ![immagine](https://user-images.githubusercontent.com/1710528/233994258-d068d27a-749a-424c-9e76-be321dd95854.png)

Yes, you can hover your mouse over the bottom left corner of the 'output-video' component, and you will notice that it is a clickable area.

**Comment by bhack** [comment]
I've tested on multiple browsers and I don't see any sensible left corner.

**Comment by yamy-cheng** [comment]
> I've tested on multiple browsers and I don't see any sensible left corner.

![image](https://user-images.githubusercontent.com/91768613/234006454-fa7706c8-a6b6-4725-be4f-0a5c7095b0fe.png)
After clicking, the output video will be displayed.

**Comment by x-ray990011** [comment]
我们现在可以达到demo1的效果。谢谢。有什么方法可以只保留选定的部分并输出视频而不保留其余部分？换句话说，它就像电影的绿布，只是保留了主体，去除了背景。

**Comment by x-ray990011** [comment]
> We can achieve the effect of demo1 now. Thank you very much. What method is there to keep only the selected part and output the video without retaining the rest? In other words, it is like the movie's green cloth, only retaining the main body and removing the background.

We can achieve the effect of demo1 now. Thank you very much. What method is there to keep only the selected part and output the video without retaining the rest? In other words, it is like the movie's green cloth, only retaining the main body and removing the background.
