### ISSUE TITLE
A series questions about the model

### ISSUE THREAD

**Issue by WIFIwifi8966** [z-x-yang/Segment-and-Track-Anything#122]
That's an excellent job! While I have few questions.
First, the project's progression from AOT to DeAOT to SAMtrack suggests that for panoramic segmentation, could AOT perform a similiar role SAMtrack, excluding the ability of clicking as a prompt?
Second, in the paper of SAMTrack, we could see the model is categorized as the VOS model. However, based on the examples presented, it seems the AOT, DeAOT, SAMTrack model could accomplish tasks simliar to MOTS, so could we conclude that this model can slove a wide range range of tasks such as VOD/VSS/VOS/MOST?
Third, the model of SAM is vit_b in the readme. Have you experimented with changing the model, such as using vit_h for testing? (Alternatively, could you guide me on where to change the model? I couldn't locate that section.)
Thank you very much!

**Comment by z-x-yang** [comment]
It's good to hear you are interested in our work.

About your questions:
1. AOT/DeAOT is a semi-supervised VOS method that takes reference images with object masks as input. Prompts, like clicking, are firstly pre-processed into object masks, which will be forwarded to AOT/DeAOT.
2. Yes. SAM-Track can handle various video tasks, including VOD/VSS/VOS/MOST.
3. To change the SAM backbone, modify the config in [here](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/model_args.py).

**Comment by WIFIwifi8966** [comment]
> It's good to hear you are interested in our work.
> 
> About your questions:
> 
> 1. AOT/DeAOT is a semi-supervised VOS method that takes reference images with object masks as input. Prompts, like clicking, are firstly pre-processed into object masks, which will be forwarded to AOT/DeAOT.
> 2. Yes. SAM-Track can handle various video tasks, including VOD/VSS/VOS/MOST.
> 3. To change the SAM backbone, modify the config in [here](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/model_args.py).

Thank you very much!!
