### ISSUE TITLE
Does it support specific object segmentation ? 

### ISSUE THREAD

**Issue by xwhkkk** [z-x-yang/Segment-and-Track-Anything#13]
Hello !

Does it project support video object segmentation in semi-supervised setting ?  how to set prompt points to focus one objects ?

Thanks for your suggestion

**Comment by tyraut** [comment]
> Hi, we have released 1.0 version which supports the interactive mode to add points by users, please check the [tutorial](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/tutorial/1.0-Version.md) to get start.

Hi,Can I specify the split target by entering a mask for a particular target in the first frame? (I saw a similar schematic in the example video)
