### ISSUE TITLE
第100張影像後都會變全影像切割

### ISSUE THREAD

**Issue by s2137127** [z-x-yang/Segment-and-Track-Anything#131]

**Comment by s2137127** [comment]
> i have same question, how do you work with it finally, i need your experience.
modify SegTracker.py line22 
self.sam_gap=99999 
works for me!

**Comment by 7788po** [comment]
> > i have same question, how do you work with it finally, i need your experience.
> > > >
> 
> 修改SegTracker.py第22行 self.sam_gap=99999

ths for sharing and i will give it a try
