### ISSUE TITLE
Image sequences 

### ISSUE THREAD

**Issue by bhack** [z-x-yang/Segment-and-Track-Anything#14]
It would be nice to have the web demo compatibile with image sequences input other then Video.
It will be easier to test it on the fly with Davis and YouTube VOS dataset

**Comment by yamy-cheng** [comment]
Hi, the current WebUI now supports input of Image-Sequence. You can try it out by following the [tutorial](https://github.com/z-x-yang/Segment-and-Track-Anything/blob/main/tutorial/tutorial%20for%20Image-Sequence%20input.md).

**Comment by bhack** [comment]
Nice!
