### ISSUE TITLE
  File "/content/Segment-and-Track-Anything/app.py", line 29, in <module>     from ast_master.prepare import ASTpredict ModuleNotFoundError: No module named 'ast_master

### ISSUE THREAD

**Issue by algint** [z-x-yang/Segment-and-Track-Anything#146]
最近的commit在colab上运行会报错，错误如题所示

**Comment by flamewindjoe** [comment]
same error

**Comment by algint** [comment]
Email has been received.                  Best regards.                              ---Hui

**Comment by little612pea** [comment]
[prepare.zip](https://github.com/z-x-yang/Segment-and-Track-Anything/files/15103913/prepare.zip)
please add this file to ./ast_master/prepare.py and it might solve this issue
the repo will be updated shortly with new tutorial ,sorry for any inconvenience caused~ #
