### ISSUE TITLE
run app.py error

### ISSUE THREAD

**Issue by guoguolord** [z-x-yang/Segment-and-Track-Anything#17]
when I run app.py，but I got a mistake ,that is "No module named 'blib2to3'".  then I install "2to3" packages ,but the mistake still exist

**Comment by yamy-cheng** [comment]
> There are also other missing undeclared dependencies like zip. Can you check it in a clean env?

Thanks for letting us know. We'll test it in a clean environment and declare the missing dependencies.

**Comment by yamy-cheng** [comment]
> We require cmdline `ffmpeg` if your dependency is `opencv-python` from pip. Please double check Gradio [gradio-app/gradio#2003](https://github.com/gradio-app/gradio/pull/2003) in a clean OS/VM/Container.

Thank you for your kind reminder, we will conduct an inspection.
