### ISSUE TITLE
new request

### ISSUE THREAD

**Issue by x-ray990011** [z-x-yang/Segment-and-Track-Anything#20]
We can achieve the effect of demo1 now. Thank you very much. What method is there to keep only the selected part and output the video without retaining the rest? In other words, it is like the movie's green cloth, only retaining the main body and removing the background.

**Comment by yamy-cheng** [comment]
Hi, you can achieve this goal by selecting the corresponding region in the original video frame using the predicted masks.

**Comment by x-ray990011** [comment]
> Hi, you can achieve this goal by selecting the corresponding region in the original video frame using the predicted masks.
I am using WEBUI and cannot obtain the mask area. How can I obtain the mask area?

**Comment by yamy-cheng** [comment]
The predicted masks will be saved in `./assets/your_video_name_masks` directory.
