### ISSUE TITLE
Run time performance

### ISSUE THREAD

**Issue by DavidTu21** [z-x-yang/Segment-and-Track-Anything#24]
Hi,

Thank you for such an amazing and useful project! I am wondering what the best performance of the running time for each frame you got when tracking an object in a video? The reason I am asking is that I am thinking to use this powerful tool in a real-time AR application but not sure whether it could be capable of this. Thank you again for your time and effort!

**Comment by yamy-cheng** [comment]
> Hi,
> 
> Thank you for such an amazing and useful project! I am wondering what the best performance of the running time for each frame you got when tracking an object in a video? The reason I am asking is that I am thinking to use this powerful tool in a real-time AR application but not sure whether it could be capable of this. Thank you again for your time and effort!

The tracking mode of SAMTrack is [DeAoT](https://github.com/yoxu515/aot-benchmark), so if you want to know the best performance, you can refer to the performance of DeAoT. We will also release the performance of SAMTrack in the next few days.

**Comment by DavidTu21** [comment]
Thank you both for your prompt response! From the result table, it seems that AOT and DeAoT could achieve a very impressive fps, I will give it a try!
