### ISSUE TITLE
APP.error

### ISSUE THREAD

**Issue by x-ray990011** [z-x-yang/Segment-and-Track-Anything#26]
When I tried the latest uploaded app. py, I found an error in the program.
![image](https://user-images.githubusercontent.com/127190335/234527581-9552bea6-dbb0-42e0-8dc1-150a39706282.png)

**Comment by bhack** [comment]
Have you checked https://github.com/z-x-yang/Segment-and-Track-Anything/issues/17#issuecomment-1519983145 ?

**Comment by yamy-cheng** [comment]
Thank you for your reminder. The missing files have been added, and you can solve this issue by cloning the repository again.
