### ISSUE TITLE
README.md TODO YouTube URLs lead to private videos

### ISSUE THREAD

**Issue by EitanHemed** [z-x-yang/Segment-and-Track-Anything#27]
The links on the [**TODO section**](https://github.com/z-x-yang/Segment-and-Track-Anything#calendartodo) _1.0-Version Interactive WebUI_ lead to private videos.

Could it be that the correct videos are referenced under [**New Features**](https://github.com/z-x-yang/Segment-and-Track-Anything#loudspeakernew-features) [2023/4/24] _Tutorial V1.0_?

**Comment by yamy-cheng** [comment]
Thank you for your reminder, the video links have been updated.

**Comment by yamy-cheng** [comment]
> The links on the [**TODO section**](https://github.com/z-x-yang/Segment-and-Track-Anything#calendartodo) _1.0-Version Interactive WebUI_ lead to private videos.
> 
> Could it be that the correct videos are referenced under [**New Features**](https://github.com/z-x-yang/Segment-and-Track-Anything#loudspeakernew-features) [2023/4/24] _Tutorial V1.0_?

The links in the TODO section for the 1.0-Version Interactive WebUI are different from the video under the New Features [2023/4/24] Tutorial V1.0. The former are demos to show the interactive ability of the WebUI, while the latter are tutorials on how to use the Interactive WebUI.

**Comment by EitanHemed** [comment]
Great, Thanks!
