### ISSUE TITLE
'groundingdino' module not found error

### ISSUE THREAD

**Issue by Davidyao99** [z-x-yang/Segment-and-Track-Anything#31]
I am following the setup steps and trying to run the demo.ipynb.

I believe this step in the install.sh downloads the necessary groundingdino module 
`pip install -e git+https://github.com/IDEA-Research/GroundingDINO.git@main#egg=GroundingDINO`

It is saying that all requirements are met. and setup was successful.

However, running the fi rst cell of demo.ipynb still throws the following error:
![image](https://user-images.githubusercontent.com/52120948/235510930-f2e707aa-7571-4897-8d87-35e965e5deaf.png)
Any one else experiencing this? I tried running on google colab and faced the same issue.

**Comment by bdytx5** [comment]
try pip install -e git+https://github.com/IDEA-Research/GroundingDINO.git@main#egg=GroundingDINO

this is in the install.sh script

**Comment by yamy-cheng** [comment]
> I am following the setup steps and trying to run the demo.ipynb.
> 
> I believe this step in the install.sh downloads the necessary groundingdino module `pip install -e git+https://github.com/IDEA-Research/GroundingDINO.git@main#egg=GroundingDINO`
> 
> It is saying that all requirements are met. and setup was successful.
> 
> However, running the fi rst cell of demo.ipynb still throws the following error: ![image](https://user-images.githubusercontent.com/52120948/235510930-f2e707aa-7571-4897-8d87-35e965e5deaf.png) Any one else experiencing this? I tried running on google colab and faced the same issue.

Hi, everything was normal when I launched the project in Colab. Do you still have this issue now?

**Comment by Davidyao99** [comment]
That is very strange, maybe I am setting it up wrongly? This is my google colab notebook.

https://colab.research.google.com/drive/172i9ZpRLxL3aoQAuTyzlzEGCAxFFoCX6?usp=sharing

curious to know what I am doing wrong, thank you so much!!

**Comment by Davidyao99** [comment]
It is working now, thanks!
