### ISSUE TITLE
Segmentation And Tracking For Video

### ISSUE THREAD

**Issue by TestPrab** [z-x-yang/Segment-and-Track-Anything#33]
I am trying to do segmentation and tracking for a particular subject in a video , but using text prompt I was able to set up the app correctly, and it was detecting the object I wanted in the first frame properly ,but it's having issues when I start tracking and it segments everything that is present in the video instead of just segmenting the required object in the video .  
I wanted to know if it's possible to segment and track anything simply based on text prompt ?

**Comment by yamy-cheng** [comment]
Hi, you can achieve your goal by adjusting the `sam-gap` parameter. When `sam-gap` is greater than the length of the video, the segment-everything function will not be called during the tracking process.

**Comment by TestPrab** [comment]
![image](https://user-images.githubusercontent.com/59395410/236605049-57d8305c-a922-4448-8af1-339e87c7e650.png)
![image](https://user-images.githubusercontent.com/59395410/236605167-62cf3e3a-c4d4-4770-8038-eefbfed38151.png)
I increased the `sam-gap` to the  `9364` , video is of 7 secs, but it's detecting lot of different objects even though I have reduced number of objects as well

**Comment by yamy-cheng** [comment]
When you change the parameters of SAM-Track, you need to click the `Reset` button to reinitialize SAM-Track.

**Comment by helionaut** [comment]
Similar question: what are the optimal settings for 600 frames of video to count, for example, cars from CCTV footage from your example? New objects appear in the top part of the image. How to find them all?

**Comment by yamy-cheng** [comment]
> Similar question: what are the optimal settings for 600 frames of video to count, for example, cars from CCTV footage from your example? New objects appear in the top part of the image. How to find them all? I was trying to use sam-gap 50, but after 50 frames, it kind of resets all the masks and shows the raw output from SAM without taking the text prompt into account.

Hi, since each video scenario is different, there is no optimal setting. However, we recommend that for long videos, if using `long-term memory`, the `max_len_long_term` should be set to avoid out-of-memory errors. You can use the latest uploaded `demo_instseg.ipynb` to reproduce examples of smart city applications.
