### ISSUE TITLE
How to reproduce demo6 on webUI app

### ISSUE THREAD

**Issue by yunhhp12** [z-x-yang/Segment-and-Track-Anything#37]
Hello! Thank you very much for the useful demo :)

I was wondering if I could reproduce the demo 6 described on the intro page on the web demo since there seems to be no way to navigate through frames.

Thanks in advance!

**Comment by yunhhp12** [comment]
comment from the author that the update is upcoming

**Comment by jowerz** [comment]
@yamy-cheng I've seen that in the current version it is possible to navigate through the frames via roll back functionality but what about selecting new objects/masks in intermediate frames like it is also shown in demo 6? Is it even possible? Please also see #144
