### ISSUE TITLE
Segmenting objects based on given bounding box

### ISSUE THREAD

**Issue by kulkarnikeerti** [z-x-yang/Segment-and-Track-Anything#38]
Hi @yamy-cheng , @yoxu515 , @z-x-yang , @lingorX 

Thanks again for the great work. I know that we can give input in text format or stroke or even click on the object which we would like to track. I would like to know if its possible with the current code base to use the object's bounding box as an input to track those objects?

Really appreciate your response.
Thanks

**Comment by yamy-cheng** [comment]
Do you mean user input a coordinate of box to select object?

**Comment by kulkarnikeerti** [comment]
@yamy-cheng , yes.

**Comment by yamy-cheng** [comment]
> @yamy-cheng , yes.

The current WebUI does not support this feature, but we will add a notebook for this in the future.
