### ISSUE TITLE
Testing - tracking objects with click or text

### ISSUE THREAD

**Issue by kulkarnikeerti** [z-x-yang/Segment-and-Track-Anything#39]
Hi, 

I understand that I can track selected objects with click or with text from `WebUI`. But, I would like to know if there is a script which I can use it to run instead of in `UI` (like we have a notebook - `demo.ipynb` to test segment everything)?
If this is not the case, could you please tell me which code runs when we give an input `text` to track in `WebUI`? so that I can look at that part of the code and understand if I can reuse for my requirements.

Thanks in advance

**Comment by yamy-cheng** [comment]
https://github.com/z-x-yang/Segment-and-Track-Anything/blob/bc0c43ee5098f258a68b52edd574179b85ab7152/SegTracker.py#L219
When we give an input text to select the objects of interest, SegTracker will call this functions to get annotations, and then DeAOT will track objects according to these annotations.

**Comment by kulkarnikeerti** [comment]
Thank you so much for referencing the code.
