### ISSUE TITLE
Interactively segment and track individual objects

### ISSUE THREAD

**Issue by EndToFx** [z-x-yang/Segment-and-Track-Anything#4]
I tried the web UI and it works, but I didn't find the direct selection described by demo1 that can be clicked on the object to interact with, where merged_mask == specific Id tracks the segmentation, it always splits them all.

**Comment by z-x-yang** [comment]
Thank you for your interest in our project! As indicated in the ReadMe, we are currently developing our WebUI App to support interactive editing and are planning to release it soon. We sincerely appreciate your patience during this process.

**Comment by z-x-yang** [comment]
The interactive WebUI has been released. Thanks for your patience.
