### ISSUE TITLE
OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by RGencsev16** [z-x-yang/Segment-and-Track-Anything#40]
Hello, when I trying to another video on 'demo.ipynb' I get 'OutOfMemoryError', I trying to increase the 'sam_gap' and it's work. But I want to work with more long videos (maybe real time video) and I try another video but this time again I get same error. Should I change the 'sam_gap' value for every trying? What  should I do, what is your suggestion?

**Comment by yamy-cheng** [comment]
Hi, may I ask which PyTorch version you are using? We recommend using PyTorch 1.10 or above. Additionally, could you please let me know the duration of your video? Each video should have different `sam_gap` according to your GPU memory, and maybe you can find some useful informations in this issue. https://github.com/z-x-yang/Segment-and-Track-Anything/issues/3#issue-1674092208

**Comment by RGencsev16** [comment]
Thank you for your answer, I use the 2.0.0 version of PyTorch, and video duration is 00:00:18, I'll try to solution in issue #3 but how can I find the right 'sam_gap' value, is it compulation or can I find with trying?

**Comment by yamy-cheng** [comment]
Under normal circumstances, a 0:0:18 video should not require high GPU memory. Do you know the size of your GPU memory? You can experiment with different 'sam-gap' values to find the optimal one.
