### ISSUE TITLE
grounding_caption value?

### ISSUE THREAD

**Issue by kulkarnikeerti** [z-x-yang/Segment-and-Track-Anything#41]
Hi @yamy-cheng

I would like to use my own video to segment and track. But, I don't understand what should be the value of `grounding_caption` in the below piece of code if I want to segment everything?

`pred_mask, annotated_frame = segtracker.detect_and_seg(frame, grounding_caption, box_threshold, text_threshold, box_size_threshold)`

With the default value I get `NameError: name 'grounding_caption' is not defined`

Thanks

**Comment by yamy-cheng** [comment]
If you want to segment all objects, you can use demo.ipynb. The demo_instseg is used to segment the object of interest.
