### ISSUE TITLE
PyTorch Correlation has been installed in the file, but there is still a missing DLL

### ISSUE THREAD

**Issue by hansgreen4396** [z-x-yang/Segment-and-Track-Anything#52]
DLL load failed while importing spatial_correlation_sampler_backend: 找不到指定的模块。
Failed to import PyTorch Correlation, For better efficiency, please install it.

**Comment by LiNO3Dy** [comment]
Thank you for your question. Make sure that PyTorch Correlation is installed on your system. You can install it using pip: pip install torch-correlation.
