### ISSUE TITLE
Remove tracked items

### ISSUE THREAD

**Issue by Davidyao99** [z-x-yang/Segment-and-Track-Anything#57]
Is it possible to remove items that were once tracked by SegTracker? How should I go about implementing this? Any help is appreciated!!

**Comment by LiNO3Dy** [comment]
We added a new function that allows users to modify redundant parts of the results. You can try it to see if it meets your needs. Thanks for the advice.

**Comment by Davidyao99** [comment]
Thank you so much, I will take a look at it! My main use case is this #61 . Is there a way to limit your total cuda memory usage so that cuda memory does not scale with video length? I have tried adjusting "long_term_memory_gap" and "max_len_long_term value" but it does not seem to work. Cuda memory still seems to be always increasing until out of memory on videos of up to 20 minutes length. Thank you!

**Comment by renyiyu** [comment]
I adjusted long_term_memory_gap and max_len_long_term  to a lower number, but the memory still keeps increasing(The video is 5 minutes with 30 fps, and there are more than 256 objects in the video). My computer has RTX 3090 with 24 G MEM
