### ISSUE TITLE
Unable to increase max_obj_num pass 255

### ISSUE THREAD

**Issue by Davidyao99** [z-x-yang/Segment-and-Track-Anything#58]
I am trying to increase the number of items tracked by SegTracker. However, even after changing the segtracker_args['max_obj_num'] parameter to > 255, it still seems to be capped at 255. Any idea how to resolve this? Thanks!

**Comment by ttancn** [comment]
> I am trying to increase the number of items tracked by SegTracker. However, even after changing the segtracker_args['max_obj_num'] parameter to > 255, it still seems to be capped at 255. Any idea how to resolve this? Thanks!

I also find this problem. Have you solved it?

**Comment by Davidyao99** [comment]
Yes, the issue is that somewhere towards the end, the mask is converted to dtype uint8. Which means values can only be 0-255. This is to ensure the visualisation works properly. I think what I did was convert it to normal int so that mask values can be >255 and converted the mask values with mod 255 for the visualisation to still work.
