### ISSUE TITLE
app.py error

### ISSUE THREAD

**Issue by Picasso-Wang** [z-x-yang/Segment-and-Track-Anything#59]
Hi, thank you for providing such a awesome project. 

When I use SAMTrack.ipynb, in the last step, I run !python app.py and meet a warning: "UserWarning: Unknown style parameter: height". 

Since in the first step, I run "!git clone https://github.com/z-x-yang/Segment-and-Track-Anything", so I believe I have adopted the latest version.

**Comment by LiNO3Dy** [comment]
Thank you for your question. There is indeed a warning message, but it does not affect the functionality of the code. We will fix this issue in the future. Thank you for bringing it to our attention.
