### ISSUE TITLE
Obj_num is not equal to np.unique(pred_mask)

### ISSUE THREAD

**Issue by haonanhe** [z-x-yang/Segment-and-Track-Anything#60]
I collect all pred_mask into an array and use np.unique(pred_mask) to acquire all obj classes. However, I find out that the result is inconsistent with obj_num or the max of the pred_mask. I'll be really grateful if you could give me some insight.

**Comment by LiNO3Dy** [comment]
This error has been corrected, please try again to verify it. If there is still a problem, you can continue to report it to us.
