### ISSUE TITLE
Cuda out of memory for very long videos

### ISSUE THREAD

**Issue by Davidyao99** [z-x-yang/Segment-and-Track-Anything#61]
Does the gpu memory usage increase linearly with video duration? Is there a way to prevent long-term memory from accumulating indefinitely? I am trying to run this on a 20 minutes long video. I tried adjusting the "max_len_long_term" but it seems like GPU memory is still being increasingly consumed as the video progresses. Thank you!

**Comment by LiNO3Dy** [comment]
Thank you for your question. Adjusting "max_len_long_term" should allow you to run longer videos without cuda out of memory. If you have adjusted the "max_len_long_term" parameter, you may need to reinitialize your model to take the new value into account.
