### ISSUE TITLE
name '_C' is not defined

### ISSUE THREAD

**Issue by liruiluo** [z-x-yang/Segment-and-Track-Anything#62]
When I run demo_instseg.ipynb"### Tuning Grounding-DINO and SAM on the First Frame for Good Initialization",then 
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded from [./ckpt/groundingdino_swint_ogc.pth](https://file+.vscode-resource.vscode-cdn.net/home/l/Downloads/Segment-and-Track-Anything/ckpt/groundingdino_swint_ogc.pth) 
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
SegTracker has been initialized
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?4f98b0aa-1e6f-4e7f-b094-abe676bfcdfa)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[9], line 33
     31 ret, frame = cap.read()
     32 frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
---> 33 pred_mask, annotated_frame = segtracker.detect_and_seg(frame, grounding_caption, box_threshold, text_threshold, box_size_threshold)
     34 torch.cuda.empty_cache()
     35 obj_ids = np.unique(pred_mask)

File [~/Downloads/Segment-and-Track-Anything/SegTracker.py:231](https://file+.vscode-resource.vscode-cdn.net/home/l/Downloads/Segment-and-Track-Anything/~/Downloads/Segment-and-Track-Anything/SegTracker.py:231), in SegTracker.detect_and_seg(self, origin_frame, grounding_caption, box_threshold, text_threshold, box_size_threshold, reset_image)
    228 bc_mask = self.origin_merged_mask
    230 # get annotated_frame and boxes
--> 231 annotated_frame, boxes = self.detector.run_grounding(origin_frame, grounding_caption, box_threshold, text_threshold)
    232 for i in range(len(boxes)):
    233     bbox = boxes[i]

File [~/miniconda3/envs/sam-track/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27](https://file+.vscode-resource.vscode-cdn.net/home/l/Downloads/Segment-and-Track-Anything/~/miniconda3/envs/sam-track/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27), in _DecoratorContextManager.__call__..decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File [~/Downloads/Segment-and-Track-Anything/tool/detector.py:71](https://file+.vscode-resource.vscode-cdn.net/home/l/Downloads/Segment-and-Track-Anything/~/Downloads/Segment-and-Track-Anything/tool/detector.py:71), in Detector.run_grounding(self, origin_frame, grounding_caption, box_threshold, text_threshold)
     67 _, image_tensor = self.image_transform_grounding(img_pil)
     68 # img_pil = self.image_transform_grounding_for_vis(img_pil)
...
     66         attention_weights,
     67     )
     68     return output

NameError: name '_C' is not defined

**Comment by chris-hndz** [comment]
This solution fixed it for me:

https://github.com/IDEA-Research/GroundingDINO/issues/8#issuecomment-1541892708
