### ISSUE TITLE
I wanna detect only the object that I want

### ISSUE THREAD

**Issue by Nacelle5242** [z-x-yang/Segment-and-Track-Anything#66]
first couple of frames can track well. but after 2s they are annotate automatically, even if i don't want other things like background.

here is my test video

![git_issue](https://github.com/z-x-yang/Segment-and-Track-Anything/assets/106233209/84bc0ea6-7b6b-4b55-b335-e0972cbcb784)

how can i fix it?

**Comment by LiNO3Dy** [comment]
Hi there! If you're experiencing issues with tracking performance, one potential solution is to increase the sam gap parameter in the advanced settings. This may help to improve the accuracy of the tracking algorithm. Give it a try and see if it helps!
