### ISSUE TITLE
Why failed tracking my own video?

### ISSUE THREAD

**Issue by ZC0102-shu** [z-x-yang/Segment-and-Track-Anything#69]
I success to track the demo video (swam) but when I change it to my own video, there is an error when trying to obtain the mask of the first frame. (when clicking: AttributeError: 'NoneType' object has no attribute 'seg_acc_click'). Is there any restriction to video type or something?

**Comment by LiNO3Dy** [comment]
Hi there! Thank you for your question. The error you encountered suggests that the video file was not successfully parsed to retrieve the first frame. Our video processing module supports common video types such as AVI, MP4, MKV, FLV, WMV, MOV, 3GP, as well as some other formats of video files and real-time video streams.
