### ISSUE TITLE
Click/text prompt resets after 100 frames

### ISSUE THREAD

**Issue by K-Maehashi** [z-x-yang/Segment-and-Track-Anything#72]
Hi, thank you for developing this great package with detailed instructions.

I was able to get it to work in the environment, but somehow the click/text prompt resets after 100 frames. When I check the tracking results in the folder, it can correctly detect the object (an animal) up to 100 frames, but it picks all objects from the 101-th frame.

Is this intended behavior?

**Comment by LiNO3Dy** [comment]
Thank you for your question. The model automatically detects and adds new objects every sam_gap frames. To solve this issue, you can adjust the default value of sam_gap in SegTrackerArgs to its maximum value.

**Comment by K-Maehashi** [comment]
Oh I see makes sense. Thank you for your reply!
