### ISSUE TITLE
Questions about running camera in real time 

### ISSUE THREAD

**Issue by 525753936** [z-x-yang/Segment-and-Track-Anything#74]
hello,  
Hope everything finds you well.
Thanks for sharing your amazing work!
I got some questions with your code. Cause I am not familiar with the principal of the segmentation, and i just wanna use it for my own application,  i just noticed that there was a parameter called "sam_gap " in the "demo.ipynb " file , which seemingly representes a new pred_mask will be generated.
What confused me was that when i tried to run the modified code on the camera in real time, it seemed that it would stuck for a few seconds, after processing 4 frames. 
Can I just change this number for higher or keep it the same? I wonder is there any technique to run it in real time? you can check the modified code anyway.
Here is modified code :
/home/zhengchen/Segment-and-Track-Anything-main/test2.py
Thanks for your marvelous work again!

**Comment by LiNO3Dy** [comment]
Thank you for your question. We recommend increasing the "sam_gap" parameter, for example to 99999, to adapt to real-time scenarios. To track new objects, our model uses the SAM for segmentation every "sam_gap" frames and adds new objects. This is why the processing time increases every "sam_gap" frames. If you have any further questions or concerns, please do not hesitate to let us know.

**Comment by 525753936** [comment]
Appreciate your patience and responds, it worked at last.
        
        Thanks.
        
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/8/2023 11:10
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            yuyang ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [z-x-yang/Segment-and-Track-Anything] Questions about running camera in real time (Issue #74)
        
      
    
  

Thank you for your question. We recommend increasing the "sam_gap" parameter, for example to 99999, to adapt to real-time scenarios. To track new objects, our model uses the SAM for segmentation every "sam_gap" frames and adds new objects. This is why the processing time increases every "sam_gap" frames. If you have any further questions or concerns, please do not hesitate to let us know.
