### ISSUE TITLE
Preparing metadata (setup.py) ... error   error: subprocess-exited-with-error      × python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by blockitigo** [z-x-yang/Segment-and-Track-Anything#81]
### when I am trying to run bash script/install.sh ,I got this error.what should I do to fix this?

Collecting wsgiref>=0.1.2 (from zip)
  Using cached https://mirrors.aliyun.com/pypi/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-eb2k702v/wsgiref_2b6809b82c154db6ad9567aed17eae33/setup.py", line 5, in <module>
          import ez_setup
        File "/tmp/pip-install-eb2k702v/wsgiref_2b6809b82c154db6ad9567aed17eae33/ez_setup/__init__.py", line 170
          print "Setuptools version",version,"or greater has been installed."
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
正克隆到 'Pytorch-Correlation-extension'...
remote: Enumerating objects: 198, done.
remote: Counting objects: 100% (60/60), done.

![bug](https://github.com/z-x-yang/Segment-and-Track-Anything/assets/71216040/fa3a54cd-d47a-455f-b5b8-50837a7bd5eb)

I have install the requirements that SAM and DeAOT need.
![图片](https://github.com/z-x-yang/Segment-and-Track-Anything/assets/71216040/14c5797d-fb0f-405c-ab1d-8d4c36aabf65)
![图片](https://github.com/z-x-yang/Segment-and-Track-Anything/assets/71216040/2b1d4a13-e8d5-4c51-ab93-b79125ccd490)

**Comment by blockitigo** [comment]
I can actually run this project,but left this error when installing the requirement

**Comment by renyiyu** [comment]
I ran into the same problem.

**Comment by blockitigo** [comment]
> 
Maybe you could ignore this error, which will not interfere with running
