### ISSUE TITLE
run so slow

### ISSUE THREAD

**Issue by blockitigo** [z-x-yang/Segment-and-Track-Anything#83]
Compare with https://github.com/gaomingqi/Track-Anything ，this project uses very little cpu and gpu.
Check with command top and nvidia-smi

**Comment by LiNO3Dy** [comment]
Thank you for your suggestion. Due to the use of Grounding-dino, SAM-Track occupies more more GPU memory compared to the other project.

**Comment by RaisoLiu** [comment]
Just remove gc.collect in the code. You will get very fast speed.
