### ISSUE TITLE
如何修改推理使用的显卡号

### ISSUE THREAD

**Issue by ql390962** [z-x-yang/Segment-and-Track-Anything#87]
我的机器上有多张显卡，但是0卡已经被占用，需要使用其他显卡。我尝试将model.args中gpu_id修改为2，但是推理依然占用0卡，导致出现以下错误。
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
请问如何才能选择其他显卡运行模型。

**Comment by hsdjkfnsfc** [comment]
For me , just set `export CUDA_VISIBLE_DEVICES=7` can solve you problem
