### ISSUE TITLE
Is there a way to add label to object/segment?

### ISSUE THREAD

**Issue by honglu-intel** [z-x-yang/Segment-and-Track-Anything#9]
Thx for the great work. It looks quite promising.

I am wandering whether there is a way to 'label' the segment/object, s.t. the algorithm (by labeling and training) could automatically recognize the same (or similar) object(s) in other videos, similar to how conventional object detection + tracking works.

**Comment by xyj176** [comment]
> Hi, the current algorithm is similar to conventional object detection + tracking. However, the automatic segmentation of SAM may not have strong semantics, i.e. it does not recognize certain classes or categories objects. To realize the automatic recognition, you may need a object detection or instance segmentation model.

How do I replace the sam model
