### ISSUE TITLE
 How did you install the zip package? 

### ISSUE THREAD

**Issue by Wangzhipeng777** [z-x-yang/Segment-and-Track-Anything#91]
Collecting wsgiref>=0.1.2 (from zip)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a2yx85dp/wsgiref_85f084237c944a1ea1ae198e406b8e85/setup.py", line 5, in <module>
          import ez_setup
        File "/tmp/pip-install-a2yx85dp/wsgiref_85f084237c944a1ea1ae198e406b8e85/ez_setup/__init__.py", line 170
          print "Setuptools version",version,"or greater has been installed."
                ^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by swrdZWJ** [comment]
i meet the same problem, how did you solve it? Thank you :)
