### ISSUE TITLE
Error：Connection errored out.

### ISSUE THREAD

**Issue by Wangzhipeng777** [z-x-yang/Segment-and-Track-Anything#92]
The console only outputs 1006 

 May I ask what error this is? How should I solve it?

**Comment by lsewcx** [comment]
可以试着挂一下梯子，也就是VPN，我挂了梯子就可以解决

**Comment by augustya07** [comment]
@lsewcx lsewcx  Can you elaborate more on how to resolve this issue? Whenever I am uploading a file I get this error

**Comment by lsewcx** [comment]
@augustya07 Since I'm in China, I need to turn on a VPN to connect to the internet，It seems to be connected to HuggingFace
